name: "Chiselled Tomcat Tests"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        ubuntu-release: ["22.04"]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build tomcat 10 image
        run: |
          ./build-tomcat-10.sh

      - name: Build tomcat 9 image
        run: |
          ./build-tomcat-9.sh

      - name: Build sample container
        run: |
          docker build -t sample sample
